gemini_api_key: ${GEMINI_API_KEY}
default_models:
  - gemini-1.5-pro
max_tokens: 1024
rate_limit:
  requests_per_minute: 3
  tiers:
    free: 3
    basic: 6
    premium: 9
  burst: true
  delay_after: 3
  delay_ms: 1000